server:
  port: 8080

spring:
  application:
    name: "authentication"
  devtools:
    add-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: ${SPRING_R2DBC_HOST_AUTH:localhost}
    port: ${SPRING_R2DBC_PORT_AUTH:5432}
    database: ${SPRING_R2DBC_DATABASE_AUTH:users}
    schema: "public"
    username: ${SPRING_R2DBC_USERNAME_AUTH:sm}
    password: ${SPRING_R2DBC_PASSWORD_AUTH:1234}

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"

routes:
  paths:
    users: "/api/v1/users"
    userByIdentityDocument: "/api/v1/users/userByIdentityDocument/{identityDocument}"
    userByEmail: "/api/v1/users/userByEmail/{email}"
    login: "/api/v1/login"

security:
  jwt:
    keys-location:
      private: ${JWT_PRIVATE_KEY:classpath:keys/private_key.pem}
      public: ${JWT_PUBLIC_KEY:classpath:keys/public_key.pem}
    expiration: 900000
