server:
  port: 8080
spring:
  application:
    name: "authentication"
  devtools:
    add-properties: false
  profiles:
    include: null

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "users"
    schema: "public"
    username: "sm"
    password: "1234"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/api/v1/users"
    userByIdentityDocument: "/api/v1/users/userByIdentityDocument/{identityDocument}"
